# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='valid_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
