# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20161108_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='model',
            new_name='cpu_model',
        ),
    ]
