# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20161109_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='model',
        ),
        migrations.AddField(
            model_name='server',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='型号'),
        ),
    ]
