# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20161109_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='型号'),
        ),
    ]
