# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_networkdevice_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='sub_asset_type',
            field=models.SmallIntegerField(choices=[(0, 'OS'), (1, '办公\\开发软件'), (2, '业务软件')], default=0, verbose_name='服务器类型'),
        ),
    ]
