# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-23 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_asset_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='creater',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='server',
            name='sub_asset_type',
            field=models.SmallIntegerField(choices=[(0, 'PC服务器'), (1, '刀片机'), (2, '小型机')], default=0, verbose_name='服务器类型'),
        ),
    ]
